package gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import shape.geometry.Box;
import shape.geometry.Cone;
import shape.geometry.Cylinder;
import shape.geometry.Sphere;

/**
 *
 * @author Rafael
 */
public class EditorRender extends javax.swing.JPanel {

    private int w, h;
    
    /**
     * Creates new form EditorRender
     */
    public EditorRender() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        System.out.println("paint(" + w + "," + h + ")");
        
        // adjust "camera"
        w = getWidth() / 2;
        h = getHeight() / 2;
        g.translate(w, h);
        
        Graphics2D g2 = (Graphics2D) g;
        g2.scale(1, -1);
        
        // TODO: draw a list of objects
        {
            /*   
            Box b = new Box(100, 20, 5);
            b.draw(g);
            */
            
            Cone c = new Cone(100, 50);
            c.draw(g);
            
            /*
            Cylinder cc = new Cylinder(50, 20);
            cc.draw(g);
            */
        /*
            Sphere s = new Sphere(50);
            s.draw(g);
            * 
            */
        }
        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
